apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 name: service-a-servicemonitor
 namespace: monitoring 
 labels:
   release: monitoring

spec:
 selector:
   matchLabels:
     project: prometheus
     tier: Monitoring
 namespaceSelector:
  matchNames:
  - dev
 endpoints:
  - interval: 2s
    port: a-service-port
    path: /metrics
  